# Generated by Django 5.1.1 on 2024-11-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
                ('answer_1', models.CharField(max_length=1000)),
                ('answer_2', models.CharField(max_length=1000)),
                ('answer_3', models.CharField(max_length=1000)),
                ('answer_4', models.CharField(max_length=1000)),
                ('correct_answer', models.CharField(choices=[('answer_1', 'Answer 1'), ('answer_2', 'Answer 2'), ('answer_3', 'Answer 3'), ('answer_4', 'Answer 4')], max_length=10)),
            ],
        ),
    ]
