# Generated by Django 5.1.1 on 2024-11-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTeam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerActionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bowl_type', models.CharField(max_length=500)),
            ],
        ),
    ]
