# Generated by Django 5.1.1 on 2024-11-05 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTeam', '0002_playeractioncategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('nationality', models.CharField(max_length=400)),
                ('Date_of_birth', models.CharField(max_length=300)),
                ('player_img', models.ImageField(blank=True, null=True, upload_to='player')),
                ('phone_number', models.CharField(max_length=400)),
                ('bowl_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowl', to='CreateTeam.playeractioncategory')),
                ('player_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='CreateTeam.playercategory')),
                ('team_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='CreateTeam.teamcategory')),
            ],
        ),
    ]
