# Generated by Django 5.1.1 on 2024-11-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTeam', '0005_remove_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='marriage_status',
            field=models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried')], default='unmarried', max_length=50),
        ),
    ]
