# Generated by Django 5.1.1 on 2024-11-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTeam', '0007_alter_player_player_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bowl_type',
            field=models.CharField(choices=[('right hand', 'Right Hand'), ('left hand', 'Left Hand')], default='spinner', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_type',
            field=models.CharField(choices=[('right hand', 'Right Hand'), ('left hand', 'Left Hand')], default='right hand', max_length=50),
        ),
    ]
