# Generated by Django 5.1.1 on 2024-11-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTeam', '0009_alter_player_bowl_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bowl_type',
            field=models.CharField(choices=[('all_rounder', 'All-Rounder'), ('spinner', 'Spinner'), ('fast_bowler', 'Fast-Bowler'), ('medium_fast_bowler', 'Medium Fast Bowler')], default='spinner', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_type',
            field=models.CharField(choices=[('right_hand', 'Right Hand'), ('left_hand', 'Left Hand')], default='right_hand', max_length=50),
        ),
    ]
