# Generated by Django 5.1.1 on 2024-11-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTeam', '0010_alter_player_bowl_type_alter_player_player_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bowl_type',
            field=models.CharField(choices=[('spinner', 'Spinner'), ('all_rounder', 'All-Rounder'), ('fast_bowler', 'Fast-Bowler'), ('medium_fast_bowler', 'Medium Fast Bowler')], default='spinner', max_length=50),
        ),
    ]
