# Generated by Django 5.1.1 on 2024-11-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTeam', '0011_alter_player_bowl_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerActionCategory',
        ),
        migrations.DeleteModel(
            name='PlayerCategory',
        ),
    ]
